server {
    listen 4174;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /healthz {
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    location / {
        try_files $uri $uri/ /external/sign/index.html;
    }
}
